In [3]:
import torch
import torch.nn as nn
emb = nn.Embedding(10, 3) # 10个词，每个词是3维向量
query = torch.LongTensor([[1, 2, 3], [4, 5, 6]])
output = emb(query)
print(output)

tensor([[[-1.8462,  0.2975,  0.9761],
         [ 0.2201,  0.7005,  0.9002],
         [-0.1408, -1.2125,  0.3602]],

        [[-1.1050,  0.1005,  0.6333],
         [ 0.8515,  1.4445, -0.5583],
         [ 3.0332, -0.0385, -0.0709]]], grad_fn=<EmbeddingBackward0>)


In [4]:
emb.weight

Parameter containing:
tensor([[ 0.2501,  0.4505,  1.9545],
        [-1.8462,  0.2975,  0.9761],
        [ 0.2201,  0.7005,  0.9002],
        [-0.1408, -1.2125,  0.3602],
        [-1.1050,  0.1005,  0.6333],
        [ 0.8515,  1.4445, -0.5583],
        [ 3.0332, -0.0385, -0.0709],
        [-0.7487,  0.1876, -0.8371],
        [ 0.2477,  0.9405, -0.5344],
        [ 0.1898,  0.9735,  1.5676]], requires_grad=True)

In [5]:
q_in = torch.LongTensor([1, 2, 3])
q_out = emb(q_in)
print(q_out)

tensor([[-1.8462,  0.2975,  0.9761],
        [ 0.2201,  0.7005,  0.9002],
        [-0.1408, -1.2125,  0.3602]], grad_fn=<EmbeddingBackward0>)
