In [17]:
# https://www.bilibili.com/video/BV1LzG1zqE7N/
# 有用的迭代器

from itertools import batched
numbers : list[int] = [1, 2, 3, 4, 5, 6, 7, 8, 9]
iter_batched = batched(numbers, n=4)
print(next(iter_batched))
print(next(iter_batched))
print(next(iter_batched))
print(next(iter_batched)) # iteration stop

(1, 2, 3, 4)
(5, 6, 7, 8)
(9,)


StopIteration: 

In [8]:
# 笛卡尔积
from itertools import product
colors: list[str] = ['r', 'g', 'b']
iter_product = product(colors, colors, colors)
for i in iter_product:
    print(''.join(i))

rrr
rrg
rrb
rgr
rgg
rgb
rbr
rbg
rbb
grr
grg
grb
ggr
ggg
ggb
gbr
gbg
gbb
brr
brg
brb
bgr
bgg
bgb
bbr
bbg
bbb


In [29]:
# pytorch数据集加载
from torch.utils.data import DataLoader, Dataset, TensorDataset
import torch

num_samples = 1000
num_features = 6
X = torch.randn(num_samples, num_features)
y = torch.randint(0, 2, (num_samples,))  # 二分类

dataset = TensorDataset(X, y) # 可迭代对象
iter_samples = iter(dataset) # 返回一个迭代器对象
print(next(iter_samples))
print(next(iter_samples))
print(next(iter_samples))
print(next(iter_samples))

dataloader = DataLoader(dataset, batch_size=32, shuffle=True, num_workers=4) # 可迭代对象
iter_batches = iter(dataloader) # 返回一个迭代器对象
print(next(iter_batches))
print(next(iter_batches))
print(next(iter_batches))

(tensor([ 2.1016, -0.5944,  0.3971, -0.4774, -1.3421, -0.7605]), tensor(1))
(tensor([-2.2214, -0.0830,  1.1329, -0.2223,  0.3197, -1.8275]), tensor(1))
(tensor([ 0.0790,  2.1508,  0.3004,  0.8337,  0.2067, -0.5776]), tensor(1))
(tensor([-1.0983, -1.2478, -0.1545,  0.0908,  1.1193, -0.7008]), tensor(0))
[tensor([[ 1.6119, -1.3410, -1.2025,  0.6254, -0.3166, -0.5764],
        [-0.0229,  0.2363, -1.1191, -0.5896,  0.6221,  0.5750],
        [ 0.5379,  0.0524, -0.2607, -0.6338, -0.7741,  0.9100],
        [ 0.1543, -1.3282, -2.0515,  0.0030, -1.3022, -0.3771],
        [-0.4281,  0.3550,  0.4894, -0.6878,  0.6214,  1.1831],
        [ 1.3421, -0.1761,  1.4144, -1.4516, -0.8558,  0.2323],
        [ 0.0566, -0.0901,  0.6152,  0.6858, -0.4055,  0.2595],
        [ 0.0832, -2.0541,  1.1298,  1.8227,  0.2286, -1.4961],
        [-0.2076,  0.4541, -1.5672, -0.3511,  0.4159,  0.8239],
        [-1.5252,  0.3637,  0.1589, -0.8961,  1.3742,  0.8323],
        [-0.9681, -0.2211, -0.3897,  1.3740,  0.8063,  

In [31]:
"""
Python 的 for 循环在底层会自动调用可迭代对象的 __iter__ 方法来获取一个迭代器，
然后通过 next() 方法逐一获取元素，直到抛出 StopIteration 异常。
"""

# 使用 for 循环迭代可迭代对象
for batch_data, batch_labels in dataloader:
    print(batch_data.shape, batch_labels.shape)
    break

# 使用 for 循环迭代迭代器
for batch_data, batch_labels in iter_batches:
    print(batch_data.shape, batch_labels.shape)
    break

torch.Size([32, 6]) torch.Size([32])
torch.Size([32, 6]) torch.Size([32])
