In [2]:
# https://zhuanlan.zhihu.com/p/1892093699342721639
# 反复抄写 RNN 的 PyTorch 实现
import torch
import torch.nn as nn

class SimpleRNN(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(SimpleRNN, self).__init__()
        self.rnn = nn.RNN(input_size, hidden_size, batch_first=True)
        self.fc = nn.Linear(hidden_size, output_size)

    def forward(self, x):
        out, _ = self.rnn(x)
        out = self.fc(out[:, -1, :])  # 只取最后一个时间步的输出
        return out

In [12]:
a = torch.rand(size=(25,))
print(a)
print(a.argmax())
print(a.argmax(dim=-1))

tensor([0.4025, 0.2183, 0.4697, 0.3516, 0.1081, 0.7151, 0.8242, 0.3197, 0.2098,
        0.6055, 0.6043, 0.6386, 0.8350, 0.7319, 0.6848, 0.1406, 0.6345, 0.0054,
        0.9902, 0.2223, 0.1986, 0.4540, 0.0775, 0.6037, 0.9281])
tensor(18)
tensor(18)


In [7]:
b = torch.rand(size=(3, 5))
print(b)
print(b.argmax(dim=1))
print(b.argmax(dim=-1))

tensor([[0.9688, 0.5959, 0.9530, 0.9658, 0.4197],
        [0.2159, 0.4013, 0.6323, 0.9860, 0.1357],
        [0.4115, 0.0835, 0.3932, 0.5063, 0.3148]])
tensor([0, 3, 3])
tensor([0, 3, 3])
